### PR TITLE
update fancybox to 3.2.5

### PR DESCRIPTION
**Pull request by maple3142**
As title, update fancybox to 3.2.5.
It has better ui like this:
preview

example: [https://blog.maple3142.net/](https://blog.maple3142.net/)

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@maple3142 hi and thank's to improve NexT.
But i think need to create something like separate repo (or at least separate branch) to new FB version.
So, if user will want new cool style or old stable style, he always can choose any version he want.
What u think about it? Separate repo or branch?

**Comment by maple3142** [comment]
I think seperate repo is ok, but how to add new option in `_config.yml`?
current:
```yaml
fancybox: true
```

if fancybox 3 in new repo:
```yaml
fancybox:
  enable: true
  version: 3 #version can only be 2 or 3
```
or
```yaml
fancybox: false #v2
fancybox3: true #v3
```

**Comment by ivan-nginx** [comment]
No, we not need new option. Need just add in dependencies and say too peoples what they can choose, what version of FB they can install.

```yml
# Fancybox. There is support for old version 2 and new version 3.
# Please, choose only any one variant, do not need to install both.
# For install 2.x: https://github.com/theme-next/theme-next-fancybox
# For install 3.x: https://github.com/theme-next/theme-next-fancybox3
fancybox: false
```

Something like that. :smiley: 

***

And, yes, need then add some uninstallation instructions because user may will want to see version 2 first and version 3 afterthat, or vice versa. So, him need to install and then uninstall each version.

Uninstall similar libs is simply: need to remove whole directory under the `source/lib`. For this repo —
 remove `source/lib/fancybox` directory, that's all. And both plugins will be under the same `fancybox` directory.

**Comment by maple3142** [comment]
okay, I just create another repo [theme-next/theme-next-fancybox3](https://github.com/theme-next/theme-next-fancybox3)

**Comment by ivan-nginx** [comment]
Yeah, cool! Easy, isn't it?

**Pull request closed without merging**
